default.nix: fix evaluation on nixos-unstable
`pkgs.haskell.packages.ghc801` doesn't exist in recent `nixos-unstable`, and
accessing a missing attribute throws an error:

❯ nix-shell
error: attribute ‘ghc801’ missing, at /Users/rkm/sync/git/personal/hnix/default.nix:6:26
(use ‘--show-trace’ to show detailed location information)

Proposed solution: use `lib.hasAttr` and `lib.attrByPath` to get it instead.