cabal: aeson < 1.5.3
1.5.3 introduced instances for `strict` & `data-fix`, some intstances overlap.

Trying to remove/sync instances results in:

```text
src/Nix/Expr/Types.hs:1:1: error:
    Exception when trying to run compile-time code:
      Constructor ‘DynamicKey‘ must only use its last 1 type variable(s) within
      the last 1 argument(s) of a data type
```