CI: Travis: fix Cachix nix-env install rights menegement
The Cachix suddenly started to fall with:

```
$ nix-env -iA cachix -f https://cachix.org/api/v1/install

error: creating directory '/Users/travis/.cache/nix/tarballs': Permission denied

The command "nix-env -iA cachix -f https://cachix.org/api/v1/install" exited with 1.
```

There are changes to macOS procedures, Nix updated to 2.2, and Cachix has big
upstream changes for macOS processes.

So fixing rights management in this way.

M  .travis.yml